//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy
    {
        public int Id { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> PhiCongAn { get; set; }
        public Nullable<double> HoaDon { get; set; }
        public Nullable<double> PhiKhac { get; set; }
        public string GhiChu { get; set; }
        public string NguoiLam { get; set; }
        public Nullable<System.DateTime> NgayTraDK { get; set; }
        public Nullable<System.DateTime> NgayTraBien { get; set; }
        public Nullable<int> IdXe { get; set; }
    }
}
