//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSuaChuaNoiBo
    {
        public int Id { get; set; }
        public Nullable<int> IdSuaChua { get; set; }
        public Nullable<int> IdPhuTung { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> PhiKhac { get; set; }
        public string GhiChu { get; set; }
    }
}
