//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHangTraNo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<double> SoTienTra { get; set; }
        public Nullable<double> ConNo { get; set; }
        public string NguoiTra { get; set; }
        public string ChungTu { get; set; }
        public Nullable<int> IdNhapHang { get; set; }
        public Nullable<double> PhiKhac { get; set; }
        public string GhiChu { get; set; }
    }
}
