//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string NguoiBan { get; set; }
        public double SoTien { get; set; }
        public Nullable<double> DaTra { get; set; }
        public Nullable<double> ConNo { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public Nullable<int> KhachHang { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTinhLai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> TongNhap { get; set; }
        public Nullable<double> Lai { get; set; }
    }
}
