//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int Id { get; set; }
        public Nullable<int> IdNhapHang { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> IdLoai { get; set; }
        public Nullable<int> IdCuaHang { get; set; }
        public string GhiChu { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string BienSo { get; set; }
        public string MauSac { get; set; }
        public Nullable<double> PhiKhac { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<double> GiaBanDeXuat { get; set; }
        public Nullable<int> Types { get; set; }
    }
}
